### ISSUE TITLE
different number of rows in psi files. Cbind error when creating the wds object

### ISSUE THREAD

**Issue by josegarciamanteiga** [betsig/GeneStructureTools#3]
When creating the wds object:
 Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 290100, 292901 

This is because it takes as input all the out.psi.gz whippet files, which of course have different number of rows but it is trying to do a cbind and yields an error at the second file.

5: stop(gettextf("arguments imply differing number of rows: %s", 
       paste(unique(nrows), collapse = ", ")), domain = NA)
4: data.frame(..., check.names = FALSE)
3: cbind(deparse.level, ...)
2: cbind(whip.all, whip[, wantedCol])
1: readWhippetPSIfiles(paste0(filePath, "/", filesPsi)) at #26

The out.psi.gz files were produced with the following command:

julia $(WHIPPET)/whippet-quant.jl \
        $< $^2 \
        --out $*.out \
        --index $^3 \
        --biascorrect \
        --circ --sam | samtools view -Su - | samtools sort - -o $*.whippet.bam

And the index:

index.jls: $(GENOME) $(GTF)
        condactivate julia;\
        julia $(WHIPPET)/whippet-index.jl \
        --fasta $< \
        --gtf $^2 \
        --index $@ \
        --suppress-low-tsl

**Comment by signalbash** [comment]
Can you check that you have the latest version (from this repository) installed? I had an older version installed somewhere and the same error 
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 331257, 331305
Came up.
Reinstalling fixed it.

**Comment by josegarciamanteiga** [comment]
Hi!,
I went back to the whippet guy and told me it was not normal to have
different rows, that is why I guess you did not expect it and the tool
threw an error. It was due to the --circ parameter I used. In this case,
the BackSplice events whippet finds are different numbers in the different
samples, making the number of rows different. I solved  it just by
eliminating them from the out.psi.gz files drastically. Also because I do
not think GeneStructureTools can handle BS events, yet.
By the way, why is it not possible to plot tracks and get transcript
information on TS and TE events? I have plenty of them in my results and
would be nice to look at them, too.

Thanks again for your help and nice tool,
Jose



--------------------------------------
Jose M. Garcia Manteiga PhD
Computational Biologist
Center for Translational Genomics and BioInformatics
Dibit2-Basilica, 4A3
San Raffaele Scientific Institute
Via Olgettina 58, 20132 Milano (MI), Italy

Tel: +39-02-2643-9211
e-mail: garciamanteiga.josemanuel@hsr.it


Il giorno mer 24 giu 2020 alle ore 02:01 betsig <notifications@github.com>
ha scritto:

**Comment by signalbash** [comment]
The reasoning behind that was that TS and TE are not neccessarily alternative splicing events, but rather alternative start/end sites as they still use the same splice sites across introns. 
Regardless, that is currently one of the things I am working in adding in now

**Comment by josegarciamanteiga** [comment]
Makes sense. I'll wait for the new feature. Thanks!
J



--------------------------------------
Jose M. Garcia Manteiga PhD
Computational Biologist
Center for Translational Genomics and BioInformatics
Dibit2-Basilica, 4A3
San Raffaele Scientific Institute
Via Olgettina 58, 20132 Milano (MI), Italy

Tel: +39-02-2643-9211
e-mail: garciamanteiga.josemanuel@hsr.it


Il giorno gio 25 giu 2020 alle ore 05:21 betsig <notifications@github.com>
ha scritto:

**Comment by signalbash** [comment]
TE/TS event processing/visualisation should now be possible in the latest version

**Comment by josegarciamanteiga** [comment]
That's great. I am building a snake pipeline and I'll try it downstream of
whippet.
Thanks
J


--------------------------------------
Jose M. Garcia Manteiga PhD
Computational Biologist
Center for Translational Genomics and BioInformatics
Dibit2-Basilica, 4A3
San Raffaele Scientific Institute
Via Olgettina 58, 20132 Milano (MI), Italy

Tel: +39-02-2643-9211
e-mail: ***@***.***


Il giorno ven 19 mar 2021 alle ore 02:35 betsig ***@***.***>
ha scritto:
